#!/usr/bin/env python3
"""Embed the setup screen's RML and RCSS into a C++ source pair.

The screen ships one document, compiled into the library, so every host serves
the same markup without installing files. Deterministic: identical assets
produce identical bytes.
"""

from __future__ import annotations

import argparse
from pathlib import Path

ASSETS = ("setup.rml", "setup.rcss")


def c_bytes(data: bytes) -> str:
    chunked = []
    line = []
    for byte in data:
        line.append(str(byte) if byte < 128 else f"static_cast<char>({byte})")
        if len(line) == 20:
            chunked.append(",".join(line))
            line = []
    if line:
        chunked.append(",".join(line))
    return ",\n  ".join(chunked)


def substitute(text: str, values: dict[str, str]) -> str:
    for token, value in values.items():
        text = text.replace("{" + token + "}", value)
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--assets", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--title", default="Setup")
    parser.add_argument("--message", default="Choose your files to continue.")
    parser.add_argument("--hint", default="")
    parser.add_argument("--footer", default="")
    args = parser.parse_args()

    # The generated arrays are NUL-terminated so consumers can build a
    # std::string from them directly; the size constants exclude the NUL.
    rml = (
        substitute(
            (args.assets / "setup.rml").read_text("utf-8"),
            {
                "TITLE": args.title,
                "MESSAGE": args.message,
                "HINT": args.hint,
                "FOOTER": args.footer,
            },
        ).encode("utf-8")
        + b"\0"
    )
    rcss = (args.assets / "setup.rcss").read_bytes() + b"\0"

    args.header.write_text(
        f"""// Generated by tools/embed_assets.py from assets/. Do not edit.
#pragma once
#include <cstddef>

namespace setup_ui::assets {{

inline constexpr std::size_t kDocumentRmlSize = {len(rml) - 1};
inline constexpr std::size_t kDocumentRcssSize = {len(rcss) - 1};
extern const char kDocumentRml[];
extern const char kDocumentRcss[];

}} // namespace setup_ui::assets
""",
        encoding="utf-8",
    )
    args.source.write_text(
        f"""// Generated by tools/embed_assets.py from assets/. Do not edit.
#include "assets.h"

namespace setup_ui::assets {{

const char kDocumentRml[] = {{
  {c_bytes(rml)}
}};

const char kDocumentRcss[] = {{
  {c_bytes(rcss)}
}};

}} // namespace setup_ui::assets
""",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
