#!/usr/bin/env python3
"""Embed the setup web assets into a C++ header/source pair.

The library compiles the page and controller into the binary so consumers
serve a complete, working setup UI from one link. Deterministic: identical
assets produce identical bytes (sorted inputs, fixed formatting).
"""

from __future__ import annotations

import argparse
from pathlib import Path

ASSETS = ("index.html", "setup.js")


def c_bytes(data: bytes) -> str:
    return ",".join(str(byte) for byte in data)


def placeholder_substitutions(
    index_html: str, title: str, message: str, hint: str, footer: str
) -> str:
    for token, value in (
        ("{TITLE}", title),
        ("{MESSAGE}", message),
        ("{HINT}", hint),
        ("{FOOTER}", footer),
    ):
        index_html = index_html.replace(token, value)
    return index_html


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--assets", type=Path, required=True, help="directory holding the assets"
    )
    parser.add_argument("--source", type=Path, required=True, help="output .cpp path")
    parser.add_argument("--header", type=Path, required=True, help="output .h path")
    parser.add_argument("--title", default="Setup")
    parser.add_argument("--message", default="Choose your files to continue.")
    parser.add_argument("--hint", default="")
    parser.add_argument("--footer", default="")
    args = parser.parse_args()

    substitutions = placeholder_substitutions(
        (args.assets / "index.html").read_text("utf-8"),
        args.title,
        args.message,
        args.hint,
        args.footer,
    )
    page = substitutions.encode("utf-8")
    script = (args.assets / "setup.js").read_bytes()

    header = f"""// Generated by tools/embed_assets.py from assets/. Do not edit.
#pragma once
#include <cstddef>

namespace setup_ui::assets {{

inline constexpr std::size_t kIndexSize = {len(page)};
inline constexpr std::size_t kScriptSize = {len(script)};
extern const unsigned char kIndexBytes[];
extern const unsigned char kScriptBytes[];

}} // namespace setup_ui::assets
"""
    args.header.write_text(header, encoding="utf-8")

    source = f"""// Generated by tools/embed_assets.py from assets/. Do not edit.
#include "{args.header.name}"

namespace setup_ui::assets {{

const unsigned char kIndexBytes[{len(page)}] = {{
{c_bytes(page)}
}};

const unsigned char kScriptBytes[{len(script)}] = {{
{c_bytes(script)}
}};

}} // namespace setup_ui::assets
"""
    args.source.write_text(source, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
